### ISSUE TITLE
error for COI assignments

### ISSUE THREAD

**Issue by mimouschka** [xapple/crest4#7]
Hi,
I am running into an error assigning COI sequences with midori253darn. Could you troubleshoot this? It seems it is a database format error.
Thanks!
    `(crest4)mibr@cno-0004:/scratch/ssd/fastwork/metabridge/methods_comparisons/2_metabridge_methods_analysis$ crest4 -t 32 --fasta swarm/COI
    _methods_comp_SWARM_parsed.fasta -d midori253darn --otu_table swarm/COI_methods_comp_SWARM_parsed.tsv -o crest4/COI/
    Running crest4 v.4.3.6
    Calling "makeblastdb" on "/scratch/ssd/fastwork/metabridge/common/crest4/midori253darn/midori253darn.fasta"...

    /scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/Bio/SearchIO/_legacy/__init__.py:12: BiopythonDeprecationWarning: The 'Bio.SearchIO._legacy' module for parsing BLAST plain text output is deprecated and will be removed in a future release of Biopython. Consider generating your BLAST output for parsing as XML or tabular format instead.
      warnings.warn(

    Traceback (most recent call last):
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/bin/crest4", line 10, in <module>
        sys.exit(main())
                 ^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/crest4/__main__.py", line 19, in main
        return magic()
               ^^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/optmagic/__init__.py", line 250, in __call__
        return instance(*extra_args, **extra_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/crest4/classify.py", line 356, in __call__
        otus_by_rank    = self.otu_info.otus_by_rank
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/plumbing/cache.py", line 86, in __get__
        else:                                      result = self.func(instance)
                                                            ^^^^^^^^^^^^^^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/crest4/otu_tables.py", line 58, in otus_by_rank
        return self(cumulative=False)
               ^^^^^^^^^^^^^^^^^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/crest4/otu_tables.py", line 112, in __call__
        ranks       = result.taxonomy.apply(tax_to_rank)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/pandas/core/series.py", line 4765, in apply
        ).apply()
          ^^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/pandas/core/apply.py", line 1201, in apply
        return self.apply_standard()
               ^^^^^^^^^^^^^^^^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/pandas/core/apply.py", line 1281, in apply_standard
        mapped = obj._map_values(
                 ^^^^^^^^^^^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/pandas/core/base.py", line 921, in _map_values
        return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/pandas/core/algorithms.py", line 1812, in map_array
        return lib.map_infer(values, mapper, convert=convert)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "lib.pyx", line 2917, in pandas._libs.lib.map_infer
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/crest4/otu_tables.py", line 111, in <lambda>
        tax_to_rank = lambda t: rank_names[len(t.split(';')) - 1]
                                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
    IndexError: list index out of range`

**Comment by mimouschka** [comment]
Hi,
I have subsampled the fasta file I need to assign to the first 1000 and the last 6000 sequences and have rerun crest assignment with and without the --otu_table option.
I did not manage to reproduce the error…which confirms it is a formatting error in the midori253darn database, leading to an error in the assignment of my fasta, somewhere between the first 1000th and last 6000th position…
`(crest4)mibr@cno-0004:/scratch/ssd/fastwork/metabridge/methods_comparisons/2_metabridge_methods_analysis$ crest4 -t 32 --fasta swarm/COI_methods_comp_SWARM_parsed_6000last.fasta -d midori253darn -o crest4/COI/test
Running crest4 v.4.3.6
/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/Bio/SearchIO/_legacy/__init__.py:12: BiopythonDeprecationWarning: The 'Bio.SearchIO._legacy' module for parsing BLAST plain text output is deprecated and will be removed in a future release of Biopython. Consider generating your BLAST output for parsing as XML or tabular format instead.
  warnings.warn(
Classification ran successfully. Results are placed in 'crest4/COI/test/assignments.txt'.
crest4/COI/test/assignments.txt`

**Comment by lanzen** [comment]
I have looked at this issue and it is bascially caused by the DARN part that contains Bacterial COI homologs in Midori having too much depth in the taxonomic tree. This is caused by intermediate ranks that should have been removed. Basically, we don't even care about taxonomic assignments of non-eukaryotic sequences and in the next release I will likely cap them to phylum rank or similar. But, for now, some temporary fix has to be done so that when CREST4 tries to look up what taxonomic rank that a too high depth (beyond "strain") corresponds to, it does not produce this index out of range error. Lucas, can you have a look at this please? I don't feel comfortable enough with the new code base to try to fix it..

**Comment by xapple** [comment]
The new version of crest that was just published `https://pypi.org/project/crest4/4.3.7/` should fix this problem. I would be grateful if you could test and report any problems. Thanks a lot.

**Comment by mimouschka** [comment]
@xapple I confirm that crest is completing successfully now :)
Thanks
