### ISSUE TITLE
error in 16S assignment after update to crest 4.3.7

### ISSUE THREAD

**Issue by mimouschka** [xapple/crest4#8]
After updating my conda environment for crest, I now have an error when assigning a 16S fasta file using silvamod138pr2, which I did not have with the previous crest version.

    (crest4)mibr@cno-0004:/scratch/ssd/fastwork/metabridge/methods_comparisons/2_metabridge_methods_analysis$ crest4 -t 32 --fasta swarm/16S_methods_comp_SWARM_parsed.fasta -
    d silvamod138pr2 --otu_table swarm/16S_methods_comp_SWARM_parsed.tsv -o crest4/16S_final/
    Running crest4 v.4.3.7
    Traceback (most recent call last):
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/bin/crest4", line 10, in <module>
        sys.exit(main())
                 ^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/crest4/__main__.py", line 19, in main
        return magic()
               ^^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/optmagic/__init__.py", line 250, in __call__
        return instance(*extra_args, **extra_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/crest4/classify.py", line 356, in __call__
        otus_by_rank    = self.otu_info.otus_by_rank
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/plumbing/cache.py", line 86, in __get__
        else:                                      result = self.func(instance)
                                                            ^^^^^^^^^^^^^^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/crest4/otu_tables.py", line 58, in otus_by_rank
        return self(cumulative=False)
               ^^^^^^^^^^^^^^^^^^^^^^
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/crest4/otu_tables.py", line 81, in __call__
        self.check_id_match()
      File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/crest4/otu_tables.py", line 77, in check_id_match
        raise ValueError(msg)
    ValueError: The sequence named 'SWARM_13377' in the table located at 'swarm/16S_methods_comp_SWARM_parsed.tsv' does not appear in the FASTA file provided at 'swarm/16S_methods_comp_SWARM_parsed.fasta'.
    

I have checked and SWARM_13377 does exist in the fasta file:

(crest4)mibr@cno-0004:/scratch/ssd/fastwork/metabridge/methods_comparisons/2_metabridge_methods_analysis$ grep "SWARM_13377" swarm/16S_methods_comp_SWARM_parsed.fasta > swarm13377.out 

does produce the expected output

**Comment by xapple** [comment]
Would like to share the FASTA file and the OTU table? The requirement is not that "SWARM_13377" merely appear somewhere in a header, it needs to be the sole ID of the sequence. Maybe that's the issue ?

**Comment by mimouschka** [comment]
yes, maybe that's the issue indeed, but looking at the fasta file, there is a sequence for that entry... weird that it worked without any errors in the previous crest version !
Attached the tsv table and the fasta file.
[16S_methods_comp_SWARM_parsed.zip](https://github.com/xapple/crest4/files/14665921/16S_methods_comp_SWARM_parsed.zip)

**Comment by xapple** [comment]
I just ran the files you posted with `crest4 v.4.3.7` and it did not raise any exceptions. Instead completing successfully by generating the two files `otus_by_rank.tsv` and `otus_cumulative.tsv`. 🤔

**Comment by mimouschka** [comment]
HI @xapple 
I ran it again, after deleting the silvamod databse files, in order for crest to download it again, and I get the same error, see below.
In order to update crest to v4.3.7, I had updated all my conda environments using `conda update --all -p /path/to/env`
I remember that during this process, it downgraded some programs and updated some others, could it be a compatibility problem? which python version do you have ? In my crest4 conda env, I have biopython v1.83, and python v3.11

````
crest4 -t 32 --fasta swarm/16S_methods_comp_SWARM_parsed.fasta -d silvamod138pr2 --otu_table swarm/16S_methods_comp_SWARM_parsed.tsv -o crest4/16S_final/
Running crest4 v.4.3.7


          ╭────────────────────────────────────────────────────────────────── Large Download ──────────────────────────────────────────────────────────────────╮
          │                                                                                                                                                    │
          │                                                                                                                                                    │
          │  The database 'silvamod138pr2' has not been downloaded yet. This process will start now and might take some time depending on your internet        │
          │  connection. Please be patient. The result will be saved to '/scratch/ssd/fastwork/metabridge/common/crest4/'. You can override this by setting    │
          │  the $CREST4_DIR environment variable.                                                                                                             │
          │                                                                                                                                                    │
          │                                                                                                                                                    │
          ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


silvamod138pr2: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 118M/118M [00:00, 8.73MiB/s]
Calling `makeblastdb` on '/scratch/ssd/fastwork/metabridge/common/crest4/silvamod138pr2/silvamod138pr2.fasta'...
Traceback (most recent call last):
  File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/bin/crest4", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/crest4/__main__.py", line 19, in main
    return magic()
           ^^^^^^^
  File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/optmagic/__init__.py", line 250, in __call__
    return instance(*extra_args, **extra_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/crest4/classify.py", line 356, in __call__
    otus_by_rank    = self.otu_info.otus_by_rank
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/plumbing/cache.py", line 86, in __get__
    else:                                      result = self.func(instance)
                                                        ^^^^^^^^^^^^^^^^^^^
  File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/crest4/otu_tables.py", line 58, in otus_by_rank
    return self(cumulative=False)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/crest4/otu_tables.py", line 81, in __call__
    self.check_id_match()
  File "/scratch/ssd/fastwork/metabridge/common/conda/crest4/lib/python3.11/site-packages/crest4/otu_tables.py", line 77, in check_id_match
    raise ValueError(msg)
ValueError: The sequence named 'SWARM_13377' in the table located at 'swarm/16S_methods_comp_SWARM_parsed.tsv' does not appear in the FASTA file provided at 'swarm/16S_methods_comp_SWARM_parsed.fasta'.```

**Comment by mimouschka** [comment]
Hi @xapple 
I have tried running crest4 again this time without using the --otu_table option.

`crest4 -t 32 --fasta swarm/16S_methods_comp_SWARM_parsed.fasta -d silvamod138pr2 -o crest4/16S_final/`

it said it it completed successfully but looking at the "assignments.txt" file (1784 KB), it does not contain the entire number of OTUs that are present in the OTU table: the last entry in the file is for "SWARM_13376", although I have close to 300,000 OTUs.
Before the update, I had successfully used crest4 on this dataset, producing an assignments.txt file of 38,391 KB.

**Comment by xapple** [comment]
To proceed with debugging in a case like this, I see three solutions:
1. A meeting where we can look at the issue and prod around your computation environment with screen sharing.
2. You can provide a copy of the computation environment with a docker file or another type of virtual machine so that I can reproduce the error here.
3. You can create a user on your computation environment that enables me to log in via SSH to reproduce the error.

**Comment by mimouschka** [comment]
Hi @xapple 
I think option 1 is the easiest for me. Let me know how to proceed for a meeting.

**Comment by xapple** [comment]
I recently revisited this error.

It appears to me the error message is not very clear. It says:

"The sequence named 'x' in the table located at 'y' does not appear in the FASTA file provided at 'z'"

While actually it's the search hits file from either blast or vsearch that is parsed and matched with the entries from the OTU table.

The inputs were large and this assignment took several days to run, so my hypothesis is that likely your search process was terminated and a partial output created.

However if the search process returns a non-zero exit code, this raises an exception in crest4. So not sure how it could have occurred.

In any case I updated the error message in the codebase.

**Comment by mimouschka** [comment]
I think I found the reason for this error, and it is related to the search hits file from blast.

When I updated the crest4 conda environment, I ran conda update --all, and this updated also blast from 2.14.0 to 2.15, which is what seems to be the problem. Indeed, using an older conda env containing Crest4.3.6, Blast2.14.0 and Python3.11.5 completes successfully and produces an assignment.txt file contain all OTUs, but, with the following warning:

"/scratch/hdd/cluster/software/Miniconda3/22.11.1-1/envs/crest4/lib/python3.11/site-packages/Bio/SearchIO/_legacy/__init__.py:12: BiopythonDeprecationWarning: The 'Bio.SearchIO._legacy' module for parsing BLAST plain text output is deprecated and will be removed in a future release of Biopython. Consider generating your BLAST output for parsing as XML or tabular format instead."

In the updated conda environment  for  crest4.3.7, blast was updated to 2.15.0 and the search hits file generated is causing the assignment process to fail, without always generating an error (The process says it completed successfully but the assignment.txt file does not contain all OTUs). I tried downgrading blast to 2.14.0, but I get a similar error...

**Comment by lanzen** [comment]
I understand that this issue is now resolved since it could never be reproduced.
